### PR TITLE
added mode line and enabled it globally

### PR DESCRIPTION
**Pull request by mofrisch**
Hi Jeffrey,
I added a mode line snippet, which acts on all types of files.

Regards, Moritz

### CODE REVIEW

**Comment by mofrisch** [comment]
You will want mode line work in all file types, not only .8th

**Comment by massung** [comment]
Why is that? Just curious since the snippet specifically uses 8th comments and 8th as the mode that it prints out.

**Comment by mofrisch** [comment]
If you have a new file without .8th ending, e.g a library, you can add the mode line and it switches automagically to 8th

**Comment by massung** [comment]
Ah that makes sense. TY.

**Comment by mofrisch** [comment]
Hi Jeffrey,

I added a task with a problem matcher, so you get a nice error report under problems,
but I am not sure, how to integrate it. Do you have an idea?

in my work-space: .vscode/tasks.json

{
   // See https://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
   "version": "2.0.0",
   "tasks": [
      {
         "label": "run 8th",
         "type": "shell",
         "command": "8th -f ${relativeFile} -e bye",
         "problemMatcher": [
            {
               "owner": "8th",
               "fileLocation": [
                  "absolute"
               ],
               "pattern": {
                  "regexp": "^(.*):.*line\\s+(\\d+)\\s+char\\s+(\\d+)\\s+in\\s+([^:]+):.*$",
                  "message": 1,
                  "line": 2,
                  "column": 3,
                  "file": 4
               }
            }
         ],
         "group": {
            "kind": "build",
            "isDefault": true
         }
      }
   ]
}

**Comment by mofrisch** [comment]
The regex has to be: ^(.*):.*line\\s+(\\d+)\\s+char\\s+(\\d+)\\s+in\\s+([^:]+):.*$
Somehow it got muddled up by the paste.

**Comment by mofrisch** [comment]
^(.*):.*line\\\\s+(\\\\d+)\\\\s+char\\\\s+(\\\\d+)\\\\s+in\\\\s+([^:]+):.*$

one more try

**Comment by massung** [comment]
I don't know. I should have some time this weekend to see if I can figure it out, though, as I'm sure there's a way.

**Comment by mofrisch** [comment]
That would be great. And thank you for incorporating my changes so fast!

Regards, Moritz

**Pull request closed without merging**
